import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';
import axios from 'axios';

export default function MovieItem({info}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Filmes :{info.info.title}
        </h1>

        <Link href={'/busca'}>Ir para buscar</Link><br></br>
        <img with={400} height={400} alt='imagem do filme' src={`https://image.tmdb.org/t/p/original${info.info.backdrop_path}`}/>
      </main>

     
    </div>
  )
}


export const getServerSideProps = async (context) => {
  const res = await fetch(`http://localhost:3000/api/movie/${context.params.id}`)
  const json = await res.json();

  return {
    props:{
      info:json
    }
  }
}