import { useState } from 'react';
import Head from 'next/head';
import axios from 'axios';
import styles from '../styles/Home.module.css';

export default function Busca() {
    const [ searchInput,setSearchInput] = useState('');
    const [ inputSearch, setInputSearch] = useState('');

    const handlerSearch = async() =>{
        if(searchInput !== ''){
            const res = await axios.get(`http://localhost:3000/api/search?q=${searchInput}`)
            console.log(res.data.list)
            setInputSearch(res.data.list)
        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Busca
                </h1>

                <input type='text' onChange={(val)=> setSearchInput(val.target.value)}/><br></br>
                <button onClick={handlerSearch}>Procurar</button>

                {inputSearch && inputSearch.map(val =>(
                    <div>
                        <h1 className={styles.title}>
                            {val.original_title}
                        </h1>
                        <img with={400} height={400} alt='imagem do filme' src={`https://image.tmdb.org/t/p/original${val.backdrop_path}`}/>
                        <p>Nota:{val.vote_average}</p>
                    </div>
                ))

                }
            </main>
            
        </div>
    )
}
