import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import axios from 'axios';

export default function Home({list}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Filmes da semana em destaques!!
        </h1>
        <Link href={'/busca'}>Ir para buscar</Link>
        <ul>
          {list.map(item =>(
              <li key={item.id}>
                <a href={`/movie/${item.id}`}>
                  <img with={400} height={400} alt='imagem do filme' src={`https://image.tmdb.org/t/p/original${item.poster_path}`}/>
                  {item.title}
                </a>  
              </li>
          ))}
        </ul>
      </main>

     
    </div>
  )
}


export const getServerSideProps = async () =>{
  const res = await axios.get('http://localhost:3000/api/trending/')

  return {
    props:{
      list:res.data.list
    }
  }
}